openapi: 3.0.1
info:
  title: Stubber API
  version: 1.0.0
servers:
- url: /api/v1
paths:
  /stub/all:
    get:
      summary: Получить все заглушки
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
        default:
          description: Fail
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_default'
  /stub:
    post:
      summary: Получить определенную заглушку
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Stub'
        required: true
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_1'
        default:
          description: Fail
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_default'
  /stub/start:
    post:
      summary: Запустить заглушку
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Stub'
        required: true
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Stub'
        default:
          description: Fail
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_default'
  /stub/stop:
    post:
      summary: Остановить заглушку
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Stub'
        required: true
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Stub'
        default:
          description: Fail
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_default'
components:
  schemas:
    Stub:
      required:
      - path
      type: object
      properties:
        jar:
          type: string
          example: credits_stub_b1.jar
        path:
          type: string
          example: /usr/WF/stubs/credits_stub_b1.jar
        state:
          type: boolean
        pid:
          type: string
          example: "77178"
        port:
          type: string
          example: "8080"
        cpu:
          type: string
          example: "10.1"
        mem:
          type: string
          example: "1.2"
      example:
        path: /usr/WF/stubs/credits_stub_b1.jar
        mem: "1.2"
        port: "8080"
        cpu: "10.1"
        jar: credits_stub_b1.jar
        pid: "77178"
        state: true
    inline_response_200:
      type: object
      properties:
        sucess:
          type: boolean
        stubs:
          type: array
          items:
            $ref: '#/components/schemas/Stub'
      example:
        sucess: true
        stubs:
        - path: /usr/WF/stubs/credits_stub_b1.jar
          mem: "1.2"
          port: "8080"
          cpu: "10.1"
          jar: credits_stub_b1.jar
          pid: "77178"
          state: true
        - path: /usr/WF/stubs/credits_stub_b1.jar
          mem: "1.2"
          port: "8080"
          cpu: "10.1"
          jar: credits_stub_b1.jar
          pid: "77178"
          state: true
    inline_response_default:
      type: object
      properties:
        sucess:
          type: boolean
    inline_response_200_1:
      type: object
      properties:
        sucess:
          type: boolean
        stub:
          $ref: '#/components/schemas/Stub'
      example:
        sucess: true
        stub:
          path: /usr/WF/stubs/credits_stub_b1.jar
          mem: "1.2"
          port: "8080"
          cpu: "10.1"
          jar: credits_stub_b1.jar
          pid: "77178"
          state: true
